import Head from 'next/head';
import '../styles/main.scss';
import { useEffect } from 'react';

export default function App({ Component, pageProps }) {
  return (
    <>
      <Head>
        <title>Fingerprint</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <Component {...pageProps} />
    </>
  );
}
